baseurl = "https://www.bobjiang.com"
title = "Bob Jiang 敏捷开发培训 敏捷认证Scrum Master"
languageCode = "zh-cn"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "UA-36175470-1" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Bob Jiang"
  bio = "Bob Jiang是全球认证的Scrum培训师（Certified Scrum Trainer），专注于Scrum培训和敏捷教练培养，帮助企业与个人取得更好的成果！[更多个人介绍](/me/)"
  avatar = "/images/bobjiang.webp"

[Params]
  subtitle = "敏捷培训 | Scrum培训 | 敏捷认证 | 敏捷开发 | 敏捷管理 | 敏捷实践" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Bob Jiang 是一名资深的敏捷教练，敏捷开发培训师，Certified Scrum Trainer，专注于敏捷培训、Scrum培训、敏捷实践、敏捷管理、敏捷领导力、组织级敏捷、系统思考、大规模敏捷、DevOps。" # Site description. Used in meta description
  copyright = "Bob Jiang" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "/img/bobjiang-logo.webp" # Logo image. Path relative to "static"
  title = "Bob Jiang 敏捷培训 敏捷认证Scrum Master" # Logo title, otherwise will use site title
  subtitle = "敏捷培训 | Scrum培训 | 敏捷认证 | 敏捷开发 | 敏捷管理 | 敏捷实践" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "jiangxb"
  twitter = "bobjiang123"
  linkedin = "xinbaojiang"
  telegram = "bobjiang"
  github = "bobjiang"
  email = "bobjiang@bobjiang.com"
  # instagram = "username"
  # gitlab = "username"
  # bitbucket = "username"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Youtube Bob Jiang Channel"
  url = "https://www.youtube.com/channel/UCY6l_ASrqbDks31hMFrtkYA"
  # icon = "layouts/partials/youtube.svg" # Optional. Path relative to "layouts/partials"
[[Params.widgets.social.custom]]
  title = "Telegram Group"
  url = "https://t.me/bobjiang123"
[[Params.widgets.social.custom]]
  title = "敏捷开发学习资源大全"
  url = "https://www.agile123.net/"
[[Params.widgets.social.custom]]  
  title = "敏捷家"
  url = "https://www.agileplus.co/"
[[Params.widgets.social.custom]]  
  title = "Scrum培训"
  url = "https://scrumtraining.cn/"
[[Params.widgets.social.custom]]  
  title = "HiBlock社区"
  url = "https://www.hiblock.net/"
[[Params.widgets.social.custom]]  
  title = "Jacky Shen"
  url = "https://www.jackyshen.com/"
[[Params.widgets.social.custom]]  
  title = "RSG China"
  url = "https://scrumgatheringchina.com/"
[[Params.widgets.social.custom]]  
  title = "报名CSM敏捷认证课程"
  url = "https://appmopev1px9533.h5.xiaoeknow.com/v1/course/column/p_5f27d789e4b0822d26880e60?type=3"

[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true  

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "agile"
    name = "敏捷"
    url = "/tags/agile/"
    weight = 2
  [[menu.main]]
    identifier = "scrum"
    name = "Scrum"
    url = "/tags/scrum/"
    parent = "agile"
    weight = 21
  [[menu.main]]
    identifier = "scaling"
    name = "规模化敏捷"
    url = "/tags/scaling/"
    parent = "agile"
    weight = 22
  [[menu.main]]
    identifier = "cases"
    name = "敏捷案例"
    url = "/tags/cases/"
    parent = "agile"
    weight = 23  
  [[menu.main]]
    identifier = "engineering"
    name = "技术实践"
    url = "/tags/engineering/"
    parent = "agile"
    weight = 24
  [[menu.main]]
    identifier = "okr"
    name = "OKR"
    url = "/tags/okr/"
    parent = "agile"
    weight = 25            
[[menu.main]]
    identifier = "services"
    name = "服务"
    url = "/tags/service/"
    weight = 3
  [[menu.main]]
    identifier = "csm"
    name = "CSM敏捷认证培训"
    url = "/tags/csm/"
    parent = "services"
    weight = 31  
    [[menu.main]]
    identifier = "cspo"
    name = "CSPO敏捷认证培训"
    url = "/tags/cspo/"
    parent = "services"
    weight = 32 
#    [[menu.main]]
#    identifier = "consulting"
#    name = "敏捷咨询"
#    url = "/tags/consulting/"
#    parent = "services"
#    weight = 33
    [[menu.main]]
    identifier = "online"
    name = "线上课"
    url = "https://appmopev1px9533.h5.xiaoeknow.com/v1/course/column/p_5f27d789e4b0822d26880e60?type=3"
    parent = "services"
    weight = 34    
[[menu.main]]
    identifier = "others"
    name = "其他"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "games"
    name = "敏捷游戏"
    url = "/tags/games/"
    parent = "others"
    weight = 41  
  [[menu.main]]
    identifier = "book"
    name = "推荐图书"
    url = "/tags/book/"
    parent = "others"
    weight = 42  
  [[menu.main]]
    identifier = "comic-agile"
    name = "敏捷漫画"
    url = "/tags/comic-agile/"
    parent = "others"
    weight = 43
  [[menu.main]]
    identifier = "weekly-report"
    name = "周报"
    url = "/tags/周报/"
    parent = "others"
    weight = 44  
[[menu.main]]
    identifier = "series"
    name = "系列文章"
    url = "/tags/series/"
    weight = 5
  [[menu.main]]
    identifier = "csm-online"
    name = "报名CSM"
    url = "https://appmopev1px9533.h5.xiaoeknow.com/v1/course/column/p_5f27d789e4b0822d26880e60?type=3"
    weight = 6
[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/me/"
    weight = 7
    